classes:
- system.linux.system.repo_local.mcp.salt
- system.linux.system.repo_local.mcp.extra
- system.linux.system.repo_local.mcp.apt_mirantis.ubuntu
- system.openssh.client.lab
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.backupninja.client.single
- system.xtrabackup.server.single
- system.reclass.storage.system.physical_control_cluster
#- system.reclass.storage.system.cicd_control_cluster
- cluster.tty.infra.maas
- cluster.tty.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/keefans/model"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$NyWQYHbw$UwiyodGBEtFzvEM/whqs7ZLygznoqdmMTfbo1ghnbuF1Gb2AQAz4AGh2N5QugCGNn0xeOTf.bA00wOuqVbMkU0"
    salt_master_host: ${_param:infra_config_deploy_address}
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: static
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
            - ${_param:dns_server01}
            - ${_param:dns_server02}
        ens4: ${_param:linux_single_interface}
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      backup: true
    minion:
      backup: true
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          classes:
          - system.backupninja.server.single
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
          classes:
#          - system.ceph.backup.server.single
          - system.backupninja.server.single
        aptly_server_node01:
          name: ${_param:aptly_server_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.cicd.aptly
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:aptly_server_control_address}
            deploy_address: ${_param:aptly_server_deploy_address}
#        cicd_control_node01:
#          params:
#            deploy_address: ${_param:cicd_control_node01_deploy_address}
#        cicd_control_node02:
#          params:
#            deploy_address: ${_param:cicd_control_node02_deploy_address}
#        cicd_control_node03:
#          params:
#            deploy_address: ${_param:cicd_control_node03_deploy_address}
