classes:
- system.linux.system.repo_local.mcp.salt
- system.linux.system.repo_local.mcp.extra
- system.linux.system.repo_local.mcp.apt_mirantis.openstack
- system.linux.system.repo_local.mcp.apt_mirantis.ubuntu
- system.linux.system.repo_local.mcp.apt_mirantis.glusterfs
- system.openssh.client.lab
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.salt_pki
- system.salt.master.pkg
- system.salt.minion.ca.salt_master
- system.salt.master.api
- system.reclass.storage.salt
- system.backupninja.client.single
- system.xtrabackup.server.single
- system.reclass.storage.system.openstack_gateway_cluster
- system.reclass.storage.system.openstack_control_cluster
- system.reclass.storage.system.openstack_proxy_cluster
- system.reclass.storage.system.openstack_database_cluster
- system.reclass.storage.system.openstack_message_queue_cluster
- system.reclass.storage.system.openstack_benchmark_single
- system.reclass.storage.system.openstack_control_upgrade_single
- system.reclass.storage.system.stacklight_log_cluster
- system.reclass.storage.system.stacklight_telemetry_cluster
- system.reclass.storage.system.stacklightv2_server_cluster
- system.reclass.storage.system.oss_cluster
- system.reclass.storage.system.ceph_mon_cluster
- system.reclass.storage.system.ceph_rgw_cluster
- system.reclass.storage.system.physical_control_cluster
- system.reclass.storage.system.cicd_control_cluster
- cluster.tty.infra.maas
- cluster.tty.infra
parameters:
  _param:
    salt_master_base_environment: prd
    reclass_data_repository: "https://github.com/keefans/model"
    reclass_data_revision: master
    reclass_config_master: ${_param:infra_config_deploy_address}
    single_address: ${_param:infra_config_address}
    deploy_address: ${_param:infra_config_deploy_address}
    proxy_address: ${_param:infra_config_proxy_address}
    public_address: ${_param:infra_config_public_address}
    storage_address: ${_param:infra_config_storage_address}
    data_address: ${_param:infra_config_data_address}
    linux_system_codename: xenial
    salt_api_password_hash: "$6$NyWQYHbw$UwiyodGBEtFzvEM/whqs7ZLygznoqdmMTfbo1ghnbuF1Gb2AQAz4AGh2N5QugCGNn0xeOTf.bA00wOuqVbMkU0"
    salt_master_host: ${_param:infra_config_deploy_address}
    backupninja_backup_host: ${_param:infra_kvm_node03_address}
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: static
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
            - ${_param:dns_server01}
            - ${_param:dns_server02}
        ens4: ${_param:linux_single_interface}
  salt:
    master:
      command_timeout: 600
      user:
        deploy:
          permissions: ${_param:salt_master_api_permissions}
      reactor:
        reclass/minion/classify:
        - salt://reclass/reactor/node_register.sls
      backup: true
    minion:
      backup: true
  reclass:
    storage:
      data_source:
        engine: local
      node:
        infra_kvm_node01:
          params:
            keepalived_vip_priority: 100
            linux_system_codename: xenial
        infra_kvm_node02:
          params:
            keepalived_vip_priority: 101
            linux_system_codename: xenial
        infra_kvm_node03:
          classes:
          - system.backupninja.server.single
          params:
            keepalived_vip_priority: 102
            linux_system_codename: xenial
          classes:
          - system.ceph.backup.server.single
          - system.backupninja.server.single
        stacklight_telemetry_node01:
          params:
            deploy_address: ${_param:stacklight_telemetry_node01_deploy_address}
        stacklight_telemetry_node02:
          params:
            deploy_address: ${_param:stacklight_telemetry_node02_deploy_address}
        stacklight_telemetry_node03:
          params:
            deploy_address: ${_param:stacklight_telemetry_node03_deploy_address}
        stacklight_log_node01:
          classes:
          - system.elasticsearch.client.single
          - system.kibana.client.single
          params:
            deploy_address: ${_param:stacklight_log_node01_deploy_address}
        stacklight_log_node02:
          params:
            deploy_address: ${_param:stacklight_log_node02_deploy_address}
        stacklight_log_node03:
          params:
            deploy_address: ${_param:stacklight_log_node03_deploy_address}
        stacklight_server_node01:
          params:
            deploy_address: ${_param:stacklight_monitor_node01_deploy_address}
        stacklight_server_node02:
          params:
            deploy_address: ${_param:stacklight_monitor_node02_deploy_address}
        stacklight_server_node03:
          params:
            deploy_address: ${_param:stacklight_monitor_node03_deploy_address}
        openstack_control_node01:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_control_node01_deploy_address}
          classes:
          - cluster.${_param:cluster_name}.openstack.control_init
        openstack_control_node02:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_control_node02_deploy_address}
        openstack_control_node03:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_control_node02_deploy_address}
        openstack_database_node01:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_database_node01_deploy_address}
          classes:
          - cluster.${_param:cluster_name}.openstack.database_init
        openstack_database_node02:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_database_node02_deploy_address}
        openstack_database_node03:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_database_node03_deploy_address}
        openstack_message_queue_node01:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_message_queue_node01_deploy_address}
        openstack_message_queue_node02:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_message_queue_node02_deploy_address}
        openstack_message_queue_node03:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_message_queue_node03_deploy_address}
        openstack_proxy_node01:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_proxy_node01_deploy_address}
        openstack_proxy_node02:
          params:
            linux_system_codename: xenial
            deploy_address: ${_param:openstack_proxy_node02_deploy_address}
        openstack_control_upgrade_node01:
          params:
            deploy_address: ${_param:openstack_upgrade_node01_deploy_address}
        openstack_gateway_node01:
          params:
            deploy_address: ${_param:openstack_gateway_node01_deploy_address}
        openstack_gateway_node02:
          params:
            deploy_address: ${_param:openstack_gateway_node02_deploy_address}
        openstack_gateway_node03:
          params:
            deploy_address: ${_param:openstack_gateway_node03_deploy_address}
        openstack_benchmark_node01:
          params:
            deploy_address: ${_param:openstack_benchmark_node01_deploy_address}
        aptly_server_node01:
          name: ${_param:aptly_server_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.cicd.aptly
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:aptly_server_control_address}
            deploy_address: ${_param:aptly_server_deploy_address}
        ceph_mon_node01:
          params:
            deploy_address: ${_param:ceph_mon_node01_deploy_address}
        ceph_mon_node02:
          params:
            deploy_address: ${_param:ceph_mon_node02_deploy_address}
        ceph_mon_node03:
          params:
            deploy_address: ${_param:ceph_mon_node03_deploy_address}
        ceph_rgw_node01:
          params:
            deploy_address: ${_param:ceph_rgw_node01_deploy_address}
        ceph_rgw_node02:
          params:
            deploy_address: ${_param:ceph_rgw_node02_deploy_address}
        ceph_rgw_node03:
          params:
            deploy_address: ${_param:ceph_rgw_node03_deploy_address}
        cicd_control_node01:
          params:
            deploy_address: ${_param:cicd_control_node01_deploy_address}
        cicd_control_node02:
          params:
            deploy_address: ${_param:cicd_control_node02_deploy_address}
        cicd_control_node03:
          params:
            deploy_address: ${_param:cicd_control_node03_deploy_address}
        openstack_compute_node001:
          name: ${_param:openstack_compute_rack01_hostname}001
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_rack01_single_subnet}.211
            deploy_address: ${_param:openstack_compute_rack01_deploy_subnet}.211
            tenant_address: ${_param:openstack_compute_rack01_tenant_subnet}.211
        openstack_compute_node002:
          name: ${_param:openstack_compute_rack01_hostname}002
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_rack01_single_subnet}.212
            deploy_address: ${_param:openstack_compute_rack01_deploy_subnet}.212
            tenant_address: ${_param:openstack_compute_rack01_tenant_subnet}.212
        openstack_compute_node003:
          name: ${_param:openstack_compute_rack01_hostname}003
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.openstack.compute
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: xenial
            single_address: ${_param:openstack_compute_rack01_single_subnet}.213
            deploy_address: ${_param:openstack_compute_rack01_deploy_subnet}.213
            tenant_address: ${_param:openstack_compute_rack01_tenant_subnet}.213
        ceph_osd_node001:
          name: ${_param:ceph_osd_rack01_hostname}001
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:reclass_config_master}
            ceph_crush_parent: rack01
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_rack01_single_subnet}.221
            deploy_address: ${_param:ceph_osd_rack01_deploy_subnet}.221
            backend_address: ${_param:ceph_osd_rack01_backend_subnet}.221
        ceph_osd_node002:
          name: ${_param:ceph_osd_rack01_hostname}002
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:reclass_config_master}
            ceph_crush_parent: rack01
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_rack01_single_subnet}.222
            deploy_address: ${_param:ceph_osd_rack01_deploy_subnet}.222
            backend_address: ${_param:ceph_osd_rack01_backend_subnet}.222
        ceph_osd_node003:
          name: ${_param:ceph_osd_rack01_hostname}003
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.ceph.osd
          params:
            salt_master_host: ${_param:reclass_config_master}
            ceph_crush_parent: rack01
            linux_system_codename: xenial
            single_address: ${_param:ceph_osd_rack01_single_subnet}.223
            deploy_address: ${_param:ceph_osd_rack01_deploy_subnet}.223
            backend_address: ${_param:ceph_osd_rack01_backend_subnet}.223


