classes:
- system.linux.system.single
- system.rsyslog.client.single
#- cluster.tty.openstack
#- cluster.tty.stacklight
#- system.heka.log_collector.single
#- system.heka.log_collector.output.telegraf
#- system.telegraf.agent
#- system.prometheus.collector
#- service.grafana.collector
#- cluster.tty.oss
#- cluster.tty.ceph
- cluster.tty.cicd
parameters:
  _param:
    # TODO: Uncomment next line "linux_system_user_sudo: true" during the deployment.
    # Don't set it "false" before you configure sudo policies and enable power users.
    linux_system_user_sudo: true
    
    apt_mk_version: "2017.12"
    salt_control_trusty_image: http://${_param:aptly_server_hostname}:8078/images/ubuntu-14-04-x64-mcp${_param:apt_mk_version}.qcow2
    salt_control_xenial_image: http://${_param:aptly_server_hostname}:8078/images/ubuntu-16-04-x64-mcp${_param:apt_mk_version}.qcow2
    local_repos: true
    aptly_server_hostname: apt01
    aptly_server_deploy_address: 192.168.10.10
    aptly_server_control_address: 192.168.11.10
    local_repo_url: ${_param:aptly_server_deploy_address}
    linux_repo_refresh_db: true
    docker_compose_image: ${_param:aptly_server_hostname}:5000/compose:1.8.0
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 192.168.11.11
    infra_config_deploy_address: 192.168.10.11

    cluster_domain: tty.local
    cluster_name: tty
    cluster_public_host: prx
    
    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0
    control_vlan: 11
    tenant_vlan: 15

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4

    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 192.168.10.1

    aptly_gpg_public_key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: GnuPG v1

      mQENBFnU98YBCACdTxOkxAJJQaQ4B9sEsh9s4MMOMxPSCwvzgGbk6HECDBhz2auF
      FfVydNbjLfoih8qdaLSmBQg8+FtdYJHEG1lekeiUETOxJnkhUFXq85KGNj9BbGBr
      m3/6Jo58pdMNdUMurAs807STvH3iTAhYymggX1u9GyjKbv24p2KMGuK1gC3W04NG
      qOQX3iwjmBWq87fX7tNLafptCq5A9TAv4Dvt1XZgGCiLI+EcPyfgNB1W/+EOOkFu
      jFdM43nm0YE3Bf4uuVR/u0REprYJfChdS6qYYgI3n2LuPyi9WMVVee+1RZmTwFcB
      cS53h+gq1GHOhj+YOwm3+ctmIoTNi26siutdABEBAAG0Kk1pcmFudGlzIE9mZmxp
      bmUgQXB0bHkgPGluZm9AbWlyYW50aXMuY29tPokBOAQTAQIAIgUCWdT3xgIbAwYL
      CQgHAwIGFQgCCQoLBBYCAwECHgECF4AACgkQpIXB3agnLgS9wQf7B2LiR4wQh7Vq
      Vwx1dKrhj0AXF7jSYfYJ/vtV6mXb0AxAxC3BVoW+KLPB+W9lHCXBRYXf1pJZIYcx
      v0rTGeqzpcxVmMIT1E4OAmZp8pFlBsFNTERG2z01kdnd3oddF3GSiP1cTg2+c9hJ
      UGJR0tAbPXDm0dXhuDD428IuSx5o4bdNdCshPYRe/P3CGG+KrySLL0/06UU2I5Mx
      f4pctRouWfrQDA6sIS+P58NKwIpXdWj1pPogJzVUJqHHyAUM8Ri+AZoXtKjqXAqN
      QNCd/xPaL9dtGxKTMDDKHvqyF5MpU3eYcEFIi79nunfC6Iaw+Izo+hYpiBlb2s6Q
      kCgR2y/f17kBDQRZ1PfGAQgA1NqQorh2cvogoU4DbRwnQKZDCCt4WnbvcJf8WZw7
      sINbqJm3pd/UjVwcPG0GFe9w7/eEdKv6N/fVMJYo/Dj34j2waN46sIBBaXi8pPuC
      rs/fV+KFGmdXNrOED8LeJ835+6eAm3W/930P1o/Rncfi7ANQr4nuSkzCoXhwo9n8
      RX70L1pYtGw1v3qMaDBKHGpZ0ZqSewSlQYclWG5EKg6ecR0wnLK9W62b5uExbexh
      7d+W22NTZ9j7SVfwHG4IleZ03B+ak0NqlKpdEA9+8QLdrQsqFN8qDHqJ46ag+5xt
      pAPmw1S2va7Gkr0BMxzdxwA5d4ZauevaEKTi5NLGdNZuHQARAQABiQEfBBgBAgAJ
      BQJZ1PfGAhsMAAoJEKSFwd2oJy4E5R4H/3XjYvsalh2g4iYEOjZ1Ld55AA+NDlnp
      eXJfEOlhxdnAvkTc1CfKdT3qaN5hG0m7sVowaeVbf4cDNwIQy+R75V73h2DQpno3
      746DDC0C2jRzDBwKrUU9Y/du3REcq4kMCnhtVBMSX6rbJoxSFdCzLu/XJd9oeXbb
      kObIeoe9FWIrswFB4NUhTHLn1bk5p8zsVbsRm3jl6ofoQmFKFoK6FauuNeB+Fc/1
      UdMpUb1Y9dpE/akgRm/79NRHKA4plQ2X/CGZu+KIw4XVn/0ilU8FbsX+KXcp8ui0
      XRqg8z44wtlroFTrnR+DgqplsellsrM+xGtZb9VrjFLeP89jzhrBWgE=
      =GLje
      -----END PGP PUBLIC KEY BLOCK-----
    
    # MaaS parameters
    infra_maas_node01_deploy_address: ${_param:infra_config_deploy_address}
    infra_maas_node01_hostname: ${_param:infra_config_hostname}
    maas_admin_username: mirantis
    maas_admin_password: r00tme
    maas_db_password: fRqC7NJrBR0x
    infra_kvm_address: 192.168.11.200
    infra_kvm_node01_address: 192.168.11.201
    infra_kvm_node02_address: 192.168.11.202
    infra_kvm_node03_address: 192.168.11.203
    infra_kvm_node01_deploy_address: 192.168.10.201
    infra_kvm_node02_deploy_address: 192.168.10.202
    infra_kvm_node03_deploy_address: 192.168.10.203
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03
    
    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
    glusterfs_node03_address: ${_param:infra_kvm_node03_address}
    linux_deploy_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:deploy_address}
      netmask: ${_param:deploy_network_netmask}
      gateway: ${_param:deploy_network_gateway}
      ipflush_onchange: true
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}
  linux:
    network:
      dhclient:
        enabled: false
      host:
        hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:hostname}
          - ${linux:network:fqdn}
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        apt01:
          address: ${_param:aptly_server_control_address}
          names:
          - ${_param:aptly_server_hostname}
          - ${_param:aptly_server_hostname}.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}

    system:
      apt:
        config:
          nosrvrecords:
            'Acquire::EnableSrvRecords': 'false'
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      local_repos: ${_param:local_repos}
      purge_repos: True
      service:
        apt-daily.timer:
          status: dead
