
classes:
- system.linux.system.repo_local.mcp.extra
- system.linux.system.repo_local.mcp.apt_mirantis.openstack
- system.linux.system.repo_local.mcp.apt_mirantis.ubuntu
- system.linux.system.repo_local.mcp.apt_mirantis.glusterfs
- system.linux.system.repo_local.mcp.apt_mirantis.saltstack_2016_3
- service.keepalived.cluster.single
- system.glusterfs.server.cluster
- system.glusterfs.server.volume.salt_pki
- system.salt.control.virt
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_benchmark_single
- system.salt.control.cluster.openstack_upgrade_single
- system.salt.control.cluster.stacklight_server_cluster
- system.salt.control.cluster.stacklight_log_cluster
- system.salt.control.cluster.stacklight_telemetry_cluster
- system.salt.control.cluster.cicd_control_cluster
- cluster.tty.cicd.gluster
- system.salt.control.cluster.ceph_mon_cluster
- system.salt.control.cluster.ceph_rgw_cluster
- cluster.tty.infra
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: ens160
    control_nic: ens192
    proxy_nic: ens224
    public_nic: ens256
    storage_nic: ens161
    data_nic: ens193
#    primary_first_nic: eth1
#    primary_second_nic: eth2
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.control:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 2
          ram: 8192
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
        openstack.proxy:
          cpu: 1
          ram: 2048
          disk_profile: xsmall
          net_profile: default
        openstack.upgrade:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 1
          ram: 2048
          disk_profile: xsmall
          net_profile: default
        opencontrail.analytics:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        stacklight.log:
          cpu: 1
          ram: 2048
          disk_profile: large
          net_profile: default
        stacklight.server:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 1
          ram: 2048
          disk_profile: large
          net_profile: default
        cicd.control:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        ceph.mon:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: default
        ceph.rgw:
          cpu: 2
          ram: 4096
          disk_profile: small
          net_profile: default
      cluster:
        internal:
          node:
            bmk01:
              image: ${_param:salt_control_xenial_image}
            ctl01:
              image: ${_param:salt_control_xenial_image}
            ctl02:
              image: ${_param:salt_control_xenial_image}
            ctl03:
              image: ${_param:salt_control_xenial_image}
            dbs01:
              image: ${_param:salt_control_xenial_image}
            dbs02:
              image: ${_param:salt_control_xenial_image}
            dbs03:
              image: ${_param:salt_control_xenial_image}
            msg01:
              image: ${_param:salt_control_xenial_image}
            msg02:
              image: ${_param:salt_control_xenial_image}
            msg03:
              image: ${_param:salt_control_xenial_image}
            prx01:
              image: ${_param:salt_control_xenial_image}
            prx02:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        eth0:
          bridge: br_mgm
          model: virtio
        eth1:
          bridge: br_ctl
          model: virtio
          
#        eth224:
#          bridge: br_pry
#        eth256:
#          bridge: br_pub
#        eth161:
#          bridge: br_sto
#        eth193:
#          bridge: br_dat
  linux:
    network:
      bridge: linux
      interface:
        ens160:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
        ens192:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:control_nic}
#        eth224:
#          enabled: true
#          type: eth
#          proto: manual
#          name: ${_param:proxy_nic}
#        eth256:
#          enabled: true
#          type: eth
#          proto: manual
#          name: ${_param:public_nic}
        eth161:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:storage_nic}
#        eth193:
#          enabled: true
#          type: eth
#          proto: manual
#          name: ${_param:data_nic}
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
          - ${_param:dns_server01}
          - ${_param:dns_server02}
          use_interfaces:
          - ${_param:deploy_nic}
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          use_interfaces:
          - ${_param:control_nic}
 #      br_pry:
 #        enabled: true
 #        type: bridge
 #        proto: static
 #        address: ${_param:proxy_address}
 #        netmask: ${_param:control_network_netmask}
 #        use_interfaces:
 #        - ${_param:proxy_nic}
 #      br_pub:
 #        enabled: true
 #        type: bridge
 #        proto: static
 #        address: ${_param:public_address}
 #         netmask: ${_param:public_network_netmask}
 #         use_interfaces:
 #         - ${_param:public_nic}
        br_sto:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:storage_address}
          netmask: ${_param:storage_network_netmask}
          use_interfaces:
          - ${_param:storage_nic}
 #       br_dat:
 #         enabled: true
 #         type: bridge
 #         proto: static
 #         address: ${_param:data_address}
 #         netmask: ${_param:data_network_netmask}
 #         use_interfaces:
 #         - ${_param:data_nic}


  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./

