classes:
- system.linux.system.repo_local.mcp.apt_mirantis.maas
- system.maas.region.single
- system.backupninja.client.single
- cluster.tty.infra
parameters:
  _param:
    backupninja_backup_host: ${_param:infra_kvm_node02_address}
    backupninja_engine: rsync
  maas:
    region:
      commissioning_scripts:
        00-maas-05-simplify-network-interfaces: /etc/maas/files/commisioning_scripts/00-maas-05-simplify-network-interfaces
      bind:
        host: ${_param:deploy_address}
      maas_config:
        main_archive: http://${_param:local_repo_url}/ubuntu
    cluster:
      region:
        host: ${_param:deploy_address}
      saltstack_repo_key: ${_param:aptly_gpg_public_key}
      saltstack_repo_trusty: "http://${_param:local_repo_url}/ubuntu-trusty ${_param:apt_mk_version} salt"
      saltstack_repo_xenial: "http://${_param:local_repo_url}/ubuntu-xenial ${_param:apt_mk_version} salt"

# Sample MaaS Configuration
  maas:
    region:
      subnets:
        deploy_network:
          cidr: 192.168.10.0/24
          fabric: deploy_network
          gateway_ip: 192.168.10.1
          iprange:
            end: 192.168.10.254
            start: 192.168.10.154
      fabrics:
        deploy_network:
          description: Fabric for deploy_network
      machines:
        kvm01:
          interface:
            mac: 00:50:56:ad:ab:a2
            subnet: deploy_network
            mode: static
            ip: ${_param:infra_kvm_node01_deploy_address}
            gateway: ${_param:deploy_network_gateway}
          power_parameters:
            manual_type: manual
        kvm02:
          interface:
            mac: 00:50:56:ad:aa:01
            subnet: deploy_network
            mode: static
            ip: ${_param:infra_kvm_node02_deploy_address}
            gateway: ${_param:deploy_network_gateway}
          power_parameters:
            manual_type: manual
        kvm03:
          interface:
            mac: 00:50:56:ad:30:67
            subnet: deploy_network
            mode: static
            ip: ${_param:infra_kvm_node03_deploy_address}
            gateway: ${_param:deploy_network_gateway}
          power_parameters:
            manual_type: manual
#        cmp001:
#          interface:
#            mac: 00:50:56:ad:b6:bf
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:openstack_compute_node001_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
#        osd001:
#          interface:
#            mac: 00:50:56:ad:b6:bf
#            subnet: deploy_network
#            mode: static
#            ip: ${_param:ceph_osd_node001_deploy_address}
#            gateway: ${_param:deploy_network_gateway}
